### ISSUE TITLE
Plans for extending the documentation

### ISSUE THREAD

**Issue by radek2s** [radek2s/Framework-Hero#3]
Main goal of this project is to gather the basic knowledge about all of that frameworks and make it easy to compare specific concepts and differences within realisation. Most basic behaviours and getting started knowledge was already presented but there is still a lot of other stuff that could be compared. So here I want to create that list what would be nice to include in this Framework-Hero project:

- [ ] Flux / Vuex / Service
- [ ] HTTP fetch/push
- [ ] Forms
- [ ] Validation
- [ ] Component Life-cycle
- [ ] Routing
